resiliencytestsuite: python3 fix
urlopen(url).read() returns bytes, this fixes:

      File "slapos.toolbox-repository/slapos/resiliencytest/suites/resiliencytestsuite.py", line 162, in _waitForCloneToBeReadyForTakeover
        while "<b>Importer script(s) of backup in progress:</b> True" in takeover_page_content:
    TypeError: a bytes-like object is required, not 'str'

errors with KVM resilience tests